### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
Even though the package is no arch, it cannot be installed for Python 3.7. It is not necessary in Python 3.7 as it is included in the core packages, still I guess we should fix the compatibility issue. 

```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

  - dataclasses -> python[version='>=3.6,<3.7']
```

**Comment by jan-janssen** [comment]
@conda-forge/dataclasses

**Comment by ericdill** [comment]
> still I guess we should fix the compatibility issue.

~@jan-janssen can you add `skip: True  # [py>37]` to the build section?~

edit: ignore me

**Comment by ocefpaf** [comment]
> still I guess we should fix the compatibility issue.

Why? That error message just tells you that you cannot install it on py37. We could build it for py37 by removing the python pin in `host` and `run` but I remember @mingwandroid had some concerns on doing that.

**Pull request closed without merging**
